import { randomElement } from './Util.js'

const style = {
  a: [
    'casual',
    'cinematic',
    'cute',
    'cyberpunk',
    'dark fantasy',
    'dystopian',
    'fantasy',
    'futuristic',
    'gothic',
    'gritty',
    'hand-drawn',
    'historical',
    'lighthearted',
    'Lovecraftian',
    'magical',
    'mature',
    'minimalist',
    'nonlinear',
    'political',
    'psychedelic',
    'realistic',
    'relaxing',
    'retro',
    'satire',
    'sci-fi',
    'stylized',
    'supernatural',
    'surreal',
    'team-based'
  ],
  an: [
    'abstract',
    'alternate history',
    'atmospheric',
    'episodic',
    'immersive',
    'open world'
  ]
}

const genre = {
  a: [
    'art game',
    'battle royale game',
    'brawler',
    'bullet hell game',
    'collectible card game',
    'dating sim',
    'dungeon crawler',
    'fighting game',
    'god game',
    'hack-and-slash game',
    'hero shooter',
    'horror game',
    'interactive movie',
    'life sim',
    'light gun shooter',
    'looter shooter',
    'metroidvania game',
    'MOBA',
    'narrative game',
    'party game',
    'platformer',
    'point-and-click adventure',
    'psychological horror game',
    'puzzle game',
    'puzzle platformer',
    'real-time strategy game',
    'rhythm game',
    'rogue-lite',
    'roguelike',
    'role-playing game',
    'sandbox game',
    'shooter',
    'simulation game',
    'souls-like game',
    'sports game',
    'stealth game',
    'survival game',
    'survival horror game',
    'tactical RPG',
    'tactical shooter',
    'text adventure',
    'tower defense game',
    'trivia game',
    'turn-based strategy game',
    'visual novel'
  ],
  an: [
    'action-adventure game',
    'action RPG',
    'endless runner'
  ]
}

const verb = [
  'abandon',
  'absorb',
  'accompany',
  'accumulate',
  'acquire',
  'activate',
  'admire',
  'adopt',
  'advise',
  'aid',
  'alert',
  'alter',
  'analyze',
  'appeal to',
  'appoint',
  'appreciate',
  'approve',
  'argue with',
  'arrange',
  'arrest',
  'assemble',
  'assess',
  'assist',
  'attach things to',
  'attack',
  'attract',
  'avoid',
  'balance',
  'become',
  'bend',
  'benefit from',
  'bet',
  'bid on',
  'bind',
  'bite',
  'block',
  'borrow',
  'break',
  'breathe on',
  'build',
  'burn',
  'bury',
  'buy',
  'call',
  'campaign for',
  'capture',
  'care for',
  'carry',
  'catch',
  'celebrate',
  'change',
  'charge',
  'chase',
  'chat with',
  'classify',
  'clean',
  'climb on',
  'cling to',
  'collect',
  'combine',
  'command',
  'comment on',
  'communicate with',
  'compete with',
  'complain about',
  'conceal',
  'concentrate on',
  'condemn',
  'confine',
  'confront',
  'construct',
  'consume',
  'contain',
  'contemplate',
  'control',
  'convert',
  'cook',
  'copy',
  'count',
  'cover',
  'crash into',
  'crawl under',
  'create',
  'criticize',
  'crush',
  'cut',
  'damage',
  'dance with',
  'date',
  'deal with',
  'decorate',
  'defend',
  'deliver',
  'demonstrate',
  'deny',
  'describe',
  'destroy',
  'detect',
  'discharge',
  'discover',
  'discuss',
  'dislike',
  'dismiss',
  'display',
  'dispose of',
  'dissolve',
  'distribute',
  'disturb',
  'dominate',
  'drag',
  'draw',
  'dream about',
  'dress',
  'drink',
  'dry',
  'earn',
  'eat',
  'elect',
  'eliminate',
  'embody',
  'embrace',
  'emerge from',
  'encounter',
  'endorse',
  'enhance',
  'enjoy',
  'escape from',
  'evaluate',
  'examine',
  'exhibit',
  'exploit',
  'explore',
  'expose',
  'extract',
  'fall on',
  'fear',
  'fetch',
  'fight',
  'find',
  'fling',
  'float over',
  'follow',
  'freeze',
  'gather',
  'gaze at',
  'generate',
  'glance at',
  'grab',
  'grow',
  'guard',
  'heat',
  'hide',
  'hit',
  'hold',
  'honor',
  'hope for',
  'howl at',
  'hunt',
  'identify',
  'ignore',
  'imagine',
  'improve',
  'inherit',
  'inhibit',
  'inspect',
  'interview',
  'invest in',
  'investigate',
  'isolate',
  'jog with',
  'jostle',
  'joust with',
  'judge',
  'juggle',
  'jump on',
  'jump over',
  'justify',
  'kick',
  'kiss',
  'knock over',
  'laugh at',
  'launch',
  'lay on',
  'lean on',
  'learn from',
  'lift',
  'locate',
  'lose',
  'maintain',
  'manage',
  'manipulate',
  'manufacture',
  'march with',
  'measure',
  'melt',
  'modify',
  'monitor',
  'observe',
  'obsess over',
  'obtain',
  'ogle',
  'oppose',
  'organize',
  'oscillate',
  'outlaw',
  'overheat',
  'overlook',
  'paint',
  'perch on',
  'personify',
  'photograph',
  'pierce',
  'pillage',
  'pinch',
  'plant',
  'play with',
  'point at',
  'poke',
  'polish',
  'pop',
  'pose with',
  'possess',
  'praise',
  'preserve',
  'print',
  'promote',
  'protect',
  'protest',
  'pull',
  'purify',
  'pursue',
  'push',
  'question',
  'rap about',
  'rate',
  'react to',
  'read about',
  'recall',
  'recommend',
  'record',
  'recover',
  'recycle',
  'refine',
  'reflect',
  'refrigerate',
  'regulate',
  'reject',
  'relax with',
  'rely on',
  'render',
  'rent',
  'repair',
  'request',
  'research',
  'respect',
  'restore',
  'retire',
  'reveal',
  'review',
  'revive',
  'ride',
  'rinse',
  'roar at',
  'roll over',
  'rotate',
  'rub',
  'ruin',
  'run with',
  'rush into',
  'sacrifice',
  'satirize',
  'save',
  'scream at',
  'scrub',
  'scrutinize',
  'search for',
  'seduce',
  'sell',
  'shake',
  'shoot',
  'shout at',
  'shower with',
  'sing to',
  'sit on',
  'smash',
  'smell',
  'spit on',
  'spray',
  'squat under',
  'stand on',
  'steal',
  'study',
  'surround',
  'swallow',
  'synthesize',
  'tackle',
  'taint',
  'tame',
  'tap',
  'taste',
  'tell stories about',
  'testify against',
  'think about',
  'thrive on',
  'throw',
  'tickle',
  'tint',
  'toast',
  'toss',
  'touch',
  'tow',
  'train',
  'transform into',
  'translate',
  'transmute',
  'transport',
  'travel with',
  'trip over',
  'twist',
  'uncover',
  'underestimate',
  'unearth',
  'unleash',
  'utilize',
  'visualize',
  'vomit on',
  'vote against',
  'vote for',
  'wait for',
  'walk with',
  'want',
  'warp',
  'wash',
  'water',
  'weaken',
  'weigh',
  'wink at',
  'worry about',
  'worship',
  'wrestle with'
]

const person = [
  { singular: 'an activist', plural: 'activists' },
  { singular: 'an actor', plural: 'actors' },
  { singular: 'an air traffic controller', plural: 'air traffic controllers' },
  { singular: 'an anthropologist', plural: 'anthropologists' },
  { singular: 'an archaeologist', plural: 'archaeologists' },
  { singular: 'an architect', plural: 'architects' },
  { singular: 'an artisan', plural: 'artisans' },
  { singular: 'an artist', plural: 'artists' },
  { singular: 'an assassin', plural: 'assassins' },
  { singular: 'an astronaut', plural: 'astronauts' },
  { singular: 'an astronomer', plural: 'astronomers' },
  { singular: 'an astrophysicist', plural: 'astrophysicists' },
  { singular: 'an athlete', plural: 'athletes' },
  { singular: 'an author', plural: 'authors' },
  { singular: 'an aviator', plural: 'aviators' },
  { singular: 'a baker', plural: 'bakers' },
  { singular: 'a barbarian', plural: 'barbarians' },
  { singular: 'a bard', plural: 'bards' },
  { singular: 'a bartender', plural: 'bartenders' },
  { singular: 'a belly dancer', plural: 'belly dancers' },
  { singular: 'a biographer', plural: 'biographers' },
  { singular: 'a biologist', plural: 'biologists' },
  { singular: 'a blacksmith', plural: 'blacksmiths' },
  { singular: 'a blogger', plural: 'bloggers' },
  { singular: 'a bodyguard', plural: 'bodyguards' },
  { singular: 'a botanist', plural: 'botanists' },
  { singular: 'a bouncer', plural: 'bouncers' },
  { singular: 'a cartographer', plural: 'cartographers' },
  { singular: 'a cartoonist', plural: 'cartoonists' },
  { singular: 'a cashier', plural: 'cashiers' },
  { singular: 'a celebrity', plural: 'celebrities' },
  { singular: 'a centenarian', plural: 'centenarians' },
  { singular: 'a CEO', plural: 'CEOs' },
  { singular: 'a chef', plural: 'chefs' },
  { singular: 'a chemist', plural: 'chemists' },
  { singular: 'a chess grandmaster', plural: 'chess grandmasters' },
  { singular: 'a chess player', plural: 'chess players' },
  { singular: 'a chiropractor', plural: 'chiropractors' },
  { singular: 'a choreographer', plural: 'choreographers' },
  { singular: 'a civil rights leader', plural: 'civil rights leaders' },
  { singular: 'a cleric', plural: 'clerics' },
  { singular: 'a climber', plural: 'climbers' },
  { singular: 'a clinical psychologist', plural: 'clinical psychologists' },
  { singular: 'a clown', plural: 'clowns' },
  { singular: 'a coach', plural: 'coaches' },
  { singular: 'a comedian', plural: 'comedians' },
  { singular: 'a composer', plural: 'composers' },
  { singular: 'a computer scientist', plural: 'computer scientists' },
  { singular: 'a conspiracy theorist', plural: 'conspiracy theorists' },
  { singular: 'a construction worker', plural: 'construction workers' },
  { singular: 'a consultant', plural: 'consultants' },
  { singular: 'a content creator', plural: 'content creators' },
  { singular: 'a cosmologist', plural: 'cosmologists' },
  { singular: 'a cosplayer', plural: 'cosplayers' },
  { singular: 'a crime boss', plural: 'crime bosses' },
  { singular: 'a critic', plural: 'critics' },
  { singular: 'a cult leader', plural: 'cult leaders' },
  { singular: 'a dancer', plural: 'dancers' },
  { singular: 'a data analyst', plural: 'data analysts' },
  { singular: 'a dentist', plural: 'dentists' },
  { singular: 'a dermatologist', plural: 'dermatologists' },
  { singular: 'a detective', plural: 'detectives' },
  { singular: 'a director', plural: 'directors' },
  { singular: 'a DJ', plural: 'DJs' },
  { singular: 'a druid', plural: 'druids' },
  { singular: 'an economist', plural: 'economists' },
  { singular: 'an engineer', plural: 'engineers' },
  { singular: 'an entomologist', plural: 'entomologists' },
  { singular: 'an entrepreneur', plural: 'entrepreneurs' },
  { singular: 'an executive producer', plural: 'executive producers' },
  { singular: 'an exotic dancer', plural: 'exotic dancers' },
  { singular: 'an explorer', plural: 'explorers' },
  { singular: 'a factory worker', plural: 'factory workers' },
  { singular: 'a fashion designer', plural: 'fashion designers' },
  { singular: 'a feminist', plural: 'feminists' },
  { singular: 'a flight attendant', plural: 'flight attendants' },
  { singular: 'a footwear designer', plural: 'footwear designers' },
  { singular: 'a game developer', plural: 'game developers' },
  { singular: 'a geneticist', plural: 'geneticists' },
  { singular: 'a geographer', plural: 'geographers' },
  { singular: 'a geologist', plural: 'geologists' },
  { singular: 'a ghostwriter', plural: 'ghostwriters' },
  { singular: 'a graphic designer', plural: 'graphic designers' },
  { singular: 'a gunsmith', plural: 'gunsmiths' },
  { singular: 'a hacker', plural: 'hackers' },
  { singular: 'a hag', plural: 'hags' },
  { singular: 'a historian', plural: 'historians' },
  { singular: 'an inventor', plural: 'inventors' },
  { singular: 'a jeweler', plural: 'jewelers' },
  { singular: 'a journalist', plural: 'journalists' },
  { singular: 'a king', plural: 'kings' },
  { singular: 'a knight', plural: 'knights' },
  { singular: 'a lawyer', plural: 'lawyers' },
  { singular: 'a librarian', plural: 'librarians' },
  { singular: 'a linguist', plural: 'linguists' },
  { singular: 'a magician', plural: 'magicians' },
  { singular: 'a make-up artist', plural: 'make-up artists' },
  { singular: 'a marine biologist', plural: 'marine biologists' },
  { singular: 'a mathematician', plural: 'mathematicians' },
  { singular: 'a mechanic', plural: 'mechanics' },
  { singular: 'a meteorologist', plural: 'meteorologists' },
  { singular: 'a midwife', plural: 'midwives' },
  { singular: 'a monk', plural: 'monks' },
  { singular: 'a musician', plural: 'musicians' },
  { singular: 'a network administrator', plural: 'network administrators' },
  { singular: 'a neurologist', plural: 'neurologists' },
  { singular: 'a neuroscientist', plural: 'neuroscientists' },
  { singular: 'a news anchor', plural: 'news anchors' },
  { singular: 'a ninja', plural: 'ninja' },
  { singular: 'a novelist', plural: 'novelists' },
  { singular: 'a nurse', plural: 'nurses' },
  { singular: 'a painter', plural: 'painters' },
  { singular: 'a paladin', plural: 'paladins' },
  { singular: 'a paleontologist', plural: 'paleontologists' },
  { singular: 'a park ranger', plural: 'park rangers' },
  { singular: 'a personal trainer', plural: 'personal trainers' },
  { singular: 'a pharmacist', plural: 'pharmacists' },
  { singular: 'a philanthropist', plural: 'philanthropists' },
  { singular: 'a philosopher', plural: 'philosophers' },
  { singular: 'a photographer', plural: 'photographers' },
  { singular: 'a physical therapist', plural: 'physical therapists' },
  { singular: 'a physician', plural: 'physicians' },
  { singular: 'a physicist', plural: 'physicists' },
  { singular: 'a pilot', plural: 'pilots' },
  { singular: 'a pirate', plural: 'pirates' },
  { singular: 'a playwright', plural: 'playwrights' },
  { singular: 'a plumber', plural: 'plumbers' },
  { singular: 'a poet', plural: 'poets' },
  { singular: 'a police officer', plural: 'police officers' },
  { singular: 'a political scientist', plural: 'political scientists' },
  { singular: 'a politician', plural: 'politicians' },
  { singular: 'a porn star', plural: 'porn stars' },
  { singular: 'a prison warden', plural: 'prison wardens' },
  { singular: 'a programmer', plural: 'programmers' },
  { singular: 'a psychiatrist', plural: 'psychiatrists' },
  { singular: 'a psychologist', plural: 'psychologists' },
  { singular: 'a queen', plural: 'queens' },
  { singular: 'a ranger', plural: 'rangers' },
  { singular: 'a reporter', plural: 'reporters' },
  { singular: 'a rogue', plural: 'rogues' },
  { singular: 'a runologist', plural: 'runologists' },
  { singular: 'a sailor', plural: 'sailors' },
  { singular: 'a school counselor', plural: 'school counselors' },
  { singular: 'a school teacher', plural: 'school teachers' },
  { singular: 'a scientist', plural: 'scientists' },
  { singular: 'a screenwriter', plural: 'screenwriters' },
  { singular: 'a scribe', plural: 'scribes' },
  { singular: 'a sculptor', plural: 'sculptors' },
  { singular: 'a sea captain', plural: 'sea captains' },
  { singular: 'a security guard', plural: 'security guards' },
  { singular: 'a singer', plural: 'singers' },
  { singular: 'a sociologist', plural: 'sociologists' },
  { singular: 'a soldier', plural: 'soldiers' },
  { singular: 'a sorcerer', plural: 'sorcerers' },
  { singular: 'a sorceress', plural: 'sorceresses' },
  { singular: 'a special agent', plural: 'special agents' },
  { singular: 'a speechwriter', plural: 'speechwriters' },
  { singular: 'a sports announcer', plural: 'sports announcers' },
  { singular: 'a startup founder', plural: 'startup founders' },
  { singular: 'a statistician', plural: 'statisticians' },
  { singular: 'a superhero', plural: 'superheroes' },
  { singular: 'a supervillain', plural: 'supervillains' },
  { singular: 'a surgeon', plural: 'surgeons' },
  { singular: 'a talk show host', plural: 'talk show hosts' },
  { singular: 'a tattoo artist', plural: 'tattoo artists' },
  { singular: 'a televangelist', plural: 'televangelists' },
  { singular: 'a theologian', plural: 'theologians' },
  { singular: 'a theoretical physicist', plural: 'theoretical physicists' },
  { singular: 'a train conductor', plural: 'train conductors' },
  { singular: 'a translator', plural: 'translators' },
  { singular: 'a ufologist', plural: 'ufologists' },
  { singular: 'a veterinarian', plural: 'veterinarians' },
  { singular: 'a video editor', plural: 'video editors' },
  { singular: 'a voice actor', plural: 'voice actors' },
  { singular: 'a warlock', plural: 'warlocks' },
  { singular: 'a web developer', plural: 'web developers' },
  { singular: 'a wedding planner', plural: 'wedding planners' },
  { singular: 'a welder', plural: 'welders' },
  { singular: 'a witch', plural: 'witches' },
  { singular: 'a wizard', plural: 'wizards' },
  { singular: 'a writer', plural: 'writers' },
  { singular: 'a yoga instructor', plural: 'yoga instructors' }
]

const animal = [
  { singular: 'a bear', plural: 'bears' },
  { singular: 'a bird', plural: 'birds' },
  { singular: 'a cat', plural: 'cats' },
  { singular: 'a chicken', plural: 'chickens' },
  { singular: 'a cow', plural: 'cows' },
  { singular: 'a deer', plural: 'deer' },
  { singular: 'a dinosaur', plural: 'dinosaurs' },
  { singular: 'a dog', plural: 'dogs' },
  { singular: 'a duck', plural: 'ducks' },
  { singular: 'an eagle', plural: 'eagles' },
  { singular: 'an elephant', plural: 'elephants' },
  { singular: 'a falcon', plural: 'falcons' },
  { singular: 'a fish', plural: 'fish' },
  { singular: 'a horse', plural: 'horses' },
  { singular: 'a kitten', plural: 'kittens' },
  { singular: 'a lion', plural: 'lions' },
  { singular: 'a monkey', plural: 'monkeys' },
  { singular: 'a pig', plural: 'pigs' },
  { singular: 'a puppy', plural: 'puppies' },
  { singular: 'a rabbit', plural: 'rabbits' },
  { singular: 'a shark', plural: 'sharks' },
  { singular: 'a snake', plural: 'snakes' },
  { singular: 'a tiger', plural: 'tigers' },
  { singular: 'a wolf', plural: 'wolves' }
]

const supernatural = [
  { singular: 'an air spirit', plural: 'air spirits' },
  { singular: 'an alien', plural: 'aliens' },
  { singular: 'an android', plural: 'androids' },
  { singular: 'an angel', plural: 'angels' },
  { singular: 'a banshee', plural: 'banshees' },
  { singular: 'a basilisk', plural: 'basilisks' },
  { singular: 'a beholder', plural: 'beholders' },
  { singular: 'a boogeyman', plural: 'boogeymen' },
  { singular: 'a centaur', plural: 'centaurs' },
  { singular: 'a chimera', plural: 'chimeras' },
  { singular: 'a chupacabra', plural: 'chupacabras' },
  { singular: 'a cockatrice', plural: 'cockatrices' },
  { singular: 'a cosmic horror', plural: 'cosmic horrors' },
  { singular: 'a cryptid', plural: 'cryptids' },
  { singular: 'a cyclops', plural: 'cyclopses' },
  { singular: 'a dark elf', plural: 'dark elves' },
  { singular: 'a demigod', plural: 'demigods' },
  { singular: 'a demon', plural: 'demons' },
  { singular: 'a devil', plural: 'devils' },
  { singular: 'a devourer', plural: 'devourers' },
  { singular: 'a djinn', plural: 'djinns' },
  { singular: 'a doppelgänger', plural: 'doppelgängers' },
  { singular: 'a dragon', plural: 'dragons' },
  { singular: 'a drake', plural: 'drakes' },
  { singular: 'a dryad', plural: 'dryads' },
  { singular: 'a dwarf', plural: 'dwarves' },
  { singular: 'an earth spirit', plural: 'earth spirits' },
  { singular: 'an elemental', plural: 'elementals' },
  { singular: 'an elf', plural: 'elves' },
  { singular: 'an ent', plural: 'ents' },
  { singular: 'your evil twin', plural: 'evil twins' },
  { singular: 'a fairy', plural: 'fairies' },
  { singular: 'a fire spirit', plural: 'fire spirits' },
  { singular: 'a faun', plural: 'fauns' },
  { singular: 'a gargoyle', plural: 'gargoyles' },
  { singular: 'a genie', plural: 'genies' },
  { singular: 'a ghost', plural: 'ghosts' },
  { singular: 'a ghoul', plural: 'ghouls' },
  { singular: 'a giant', plural: 'giants' },
  { singular: 'a giant crab', plural: 'giant crabs' },
  { singular: 'a giant rat', plural: 'giant rats' },
  { singular: 'a giant robot', plural: 'giant robots' },
  { singular: 'a giant snake', plural: 'giant snakes' },
  { singular: 'a giant spider', plural: 'giant spiders' },
  { singular: 'a giant tortoise', plural: 'giant tortoises' },
  { singular: 'a gnome', plural: 'gnomes' },
  { singular: 'a goblin', plural: 'goblins' },
  { singular: 'a god', plural: 'gods' },
  { singular: 'a goddess', plural: 'goddesses' },
  { singular: 'a gorgon', plural: 'gorgons' },
  { singular: 'a gremlin', plural: 'gremlins' },
  { singular: 'a griffon', plural: 'griffons' },
  { singular: 'a harpy', plural: 'harpies' },
  { singular: 'a hellhound', plural: 'hellhounds' },
  { singular: 'a hobgoblin', plural: 'hobgoblins' },
  { singular: 'a hydra', plural: 'hydras' },
  { singular: 'an imp', plural: 'imps' },
  { singular: 'an incubus', plural: 'incubuses' },
  { singular: 'a jackalope', plural: 'jackalopes' },
  { singular: 'a jotun', plural: 'jotun' },
  { singular: 'a kappa', plural: 'kappas' },
  { singular: 'a kraken', plural: 'krakens' },
  { singular: 'a leprechaun', plural: 'leprechauns' },
  { singular: 'a lich', plural: 'liches' },
  { singular: 'a light elf', plural: 'light elves' },
  { singular: 'a lost soul', plural: 'lost souls' },
  { singular: 'a manticore', plural: 'manticores' },
  { singular: 'a mermaid', plural: 'mermaids' },
  { singular: 'a merman', plural: 'mermen' },
  { singular: 'a minotaur', plural: 'minotaurs' },
  { singular: 'a monster', plural: 'monsters' },
  { singular: 'a mutant', plural: 'mutants' },
  { singular: 'a necromancer', plural: 'necromancers' },
  { singular: 'a nymph', plural: 'nymphs' },
  { singular: 'an ogre', plural: 'ogres' },
  { singular: 'an oni', plural: 'oni' },
  { singular: 'an orc', plural: 'orcs' },
  { singular: 'a phoenix', plural: 'phoenixes' },
  { singular: 'a pixie', plural: 'pixies' },
  { singular: 'a robot', plural: 'robots' },
  { singular: 'a rodent of unusual size', plural: 'rodents of unusual size' },
  { singular: 'a satyr', plural: 'satyrs' },
  { singular: 'a sea monster', plural: 'sea monsters' },
  { singular: 'a sea serpent', plural: 'sea serpents' },
  { singular: 'a shade', plural: 'shades' },
  { singular: 'a sphinx', plural: 'sphinxes' },
  { singular: 'a spirit', plural: 'spirits' },
  { singular: 'a shapeshifter', plural: 'shapeshifters' },
  { singular: 'a skeleton warrior', plural: 'skeleton warriors' },
  { singular: 'a succubus', plural: 'succubuses' },
  { singular: 'a swamp monster', plural: 'swamp monsters' },
  { singular: 'a tengu', plural: 'tengu' },
  { singular: 'a titan', plural: 'titans' },
  { singular: 'a troll', plural: 'trolls' },
  { singular: 'an undead', plural: 'undead' },
  { singular: 'an undead mummy', plural: 'undead mummies' },
  { singular: 'an undead skeleton', plural: 'undead skeletons' },
  { singular: 'a unicorn', plural: 'unicorns' },
  { singular: 'an unspeakable horror', plural: 'unspeakable horrors' },
  { singular: 'a valkyrie', plural: 'valkyries' },
  { singular: 'a vampire', plural: 'vampires' },
  { singular: 'a water spirit', plural: 'water spirits' },
  { singular: 'a wendigo', plural: 'wendigos' },
  { singular: 'a werewolf', plural: 'werewolves' },
  { singular: 'a will-o\'-the-wisp', plural: 'will-o\'-the-wisps' },
  { singular: 'a wraith', plural: 'wraiths' },
  { singular: 'a wyvern', plural: 'wyverns' },
  { singular: 'a yeti', plural: 'yetis' },
  { singular: 'a zombie', plural: 'zombies' }
]

const object = [
  { singular: 'an airship', plural: 'airships' },
  { singular: 'an airplane', plural: 'airplanes' },
  { singular: 'an appliance', plural: 'appliances' },
  { singular: 'an assault rifle', plural: 'assault rifles' },
  { singular: 'an asteroid', plural: 'asteroids' },
  { singular: 'an atom', plural: 'atoms' },
  { singular: 'an automatic rifle', plural: 'automatic rifles' },
  { singular: 'a ballista', plural: 'ballistae' },
  { singular: 'a baseball bat', plural: 'baseball bats' },
  { singular: 'a battering ram', plural: 'battering rams' },
  { singular: 'a battle axe', plural: 'battle axes' },
  { singular: 'a beer', plural: 'beers' },
  { singular: 'a bicycle', plural: 'bicycles' },
  { singular: 'a black hole', plural: 'black holes' },
  { singular: 'a blimp', plural: 'blimps' },
  { singular: 'a boat', plural: 'boats' },
  { singular: 'a book', plural: 'books' },
  { singular: 'a bottle', plural: 'bottles' },
  { singular: 'a slice of bread', plural: 'a loaf of bread' },
  { singular: 'a brick', plural: 'bricks' },
  { singular: 'a brownie', plural: 'brownies' },
  { singular: 'a burrito', plural: 'burritos' },
  { singular: 'a bus', plural: 'buses' },
  { singular: 'a cake', plural: 'cakes' },
  { singular: 'a candy', plural: 'candies' },
  { singular: 'a cannon', plural: 'cannons' },
  { singular: 'a car', plural: 'cars' },
  { singular: 'a catapult', plural: 'catapults' },
  { singular: 'a bowl of cereal', plural: 'bowls of cereal' },
  { singular: 'cheese', plural: 'cheese' },
  { singular: 'a cheeseburger', plural: 'cheeseburgers' },
  { singular: 'a chili pepper', plural: 'chili peppers' },
  { singular: 'a church', plural: 'churches' },
  { singular: 'a cider', plural: 'ciders' },
  { singular: 'a cloud', plural: 'clouds' },
  { singular: 'a club', plural: 'clubs' },
  { singular: 'a cocktail', plural: 'cocktails' },
  { singular: 'a cup of coffee', plural: 'cups of coffee' },
  { singular: 'a comet', plural: 'comets' },
  { singular: 'a computer', plural: 'computers' },
  { singular: 'a cookie', plural: 'cookies' },
  { singular: 'a cricket bat', plural: 'cricket bats' },
  { singular: 'a crossbow', plural: 'crossbows' },
  { singular: 'a cruise ship', plural: 'cruise ships' },
  { singular: 'a cube', plural: 'cubes' },
  { singular: 'a dad joke', plural: 'dad jokes' },
  { singular: 'a dagger', plural: 'daggers' },
  { singular: 'a delivery truck', plural: 'delivery trucks' },
  { singular: 'DNA', plural: 'DNA' },
  { singular: 'a doughnut', plural: 'doughnuts' },
  { singular: 'a dumbbell', plural: 'dumbbells' },
  { singular: 'a dumpling', plural: 'dumplings' },
  { singular: 'an egg', plural: 'eggs' },
  { singular: 'an energy drink', plural: 'energy drinks' },
  { singular: 'an equation', plural: 'equations' },
  { singular: 'an experimental aircraft', plural: 'experimental aircraft' },
  { singular: 'a farm', plural: 'farms' },
  { singular: 'a fighter jet', plural: 'fighter jets' },
  { singular: 'a fire', plural: 'fires' },
  { singular: 'a fire extinguisher', plural: 'fire extinguishers' },
  { singular: 'a fireball', plural: 'fireballs' },
  { singular: 'a flail', plural: 'flails' },
  { singular: 'a fruit', plural: 'fruits' },
  { singular: 'a gif', plural: 'gifs' },
  { singular: 'a gift', plural: 'gifts' },
  { singular: 'a golf ball', plural: 'golf balls' },
  { singular: 'a golf club', plural: 'golf clubs' },
  { singular: 'a halberd', plural: 'halberds' },
  { singular: 'a hamburger', plural: 'hamburgers' },
  { singular: 'a handgun', plural: 'handguns' },
  { singular: 'a helicopter', plural: 'helicopters' },
  { singular: 'a hot air balloon', plural: 'hot air balloons' },
  { singular: 'a cup of hot chocolate', plural: 'cups of hot chocolate' },
  { singular: 'a hot dog', plural: 'hot dogs' },
  { singular: 'a house', plural: 'houses' },
  { singular: 'a hurricane', plural: 'hurricanes' },
  { singular: 'a bowl of ice cream', plural: 'bowls of ice cream' },
  { singular: 'a cup of juice', plural: 'cups of juice' },
  { singular: 'a katana', plural: 'katanas' },
  { singular: 'a knife', plural: 'knives' },
  { singular: 'a lance', plural: 'lances' },
  { singular: 'a laptop', plural: 'laptops' },
  { singular: 'a bottle of liquor', plural: 'bottles of liquor' },
  { singular: 'a longbow', plural: 'longbows' },
  { singular: 'a longsword', plural: 'longswords' },
  { singular: 'a mace', plural: 'maces' },
  { singular: 'a machine gun', plural: 'machine guns' },
  { singular: 'a magazine', plural: 'magazines' },
  { singular: 'a maul', plural: 'mauls' },
  { singular: 'a meat', plural: 'meats' },
  { singular: 'a meteor', plural: 'meteors' },
  { singular: 'a minivan', plural: 'minivans' },
  { singular: 'a mobile app', plural: 'mobile apps' },
  { singular: 'a morning star', plural: 'morning stars' },
  { singular: 'a mortar', plural: 'mortars' },
  { singular: 'a motor boat', plural: 'motor boats' },
  { singular: 'a motorcycle', plural: 'motorcycles' },
  { singular: 'a movie', plural: 'movies' },
  { singular: 'a mustache', plural: 'mustaches' },
  { singular: 'a nacho', plural: 'nachos' },
  { singular: 'a nebula', plural: 'nebulae' },
  { singular: 'a newspaper', plural: 'newspapers' },
  { singular: 'a noodle', plural: 'noodles' },
  { singular: 'a nuclear reactor', plural: 'nuclear reactors' },
  { singular: 'a nut', plural: 'nuts' },
  { singular: 'a particle', plural: 'particles' },
  { singular: 'a particle accelerator', plural: 'particle accelerators' },
  { singular: 'a photo', plural: 'photos' },
  { singular: 'a pie', plural: 'pies' },
  { singular: 'a pike', plural: 'pikes' },
  { singular: 'a pipe', plural: 'pipes' },
  { singular: 'a pizza', plural: 'pizzas' },
  { singular: 'a plant', plural: 'plants' },
  { singular: 'a playing card', plural: 'playing cards' },
  { singular: 'a polygon', plural: 'polygons' },
  { singular: 'a programming language', plural: 'programming languages' },
  { singular: 'a pyramid', plural: 'pyramids' },
  { singular: 'a race car', plural: 'race cars' },
  { singular: 'a rapier', plural: 'rapiers' },
  { singular: 'a recurve bow', plural: 'recurve bows' },
  { singular: 'a bowl of rice', plural: 'rice' },
  { singular: 'a rifle', plural: 'rifles' },
  { singular: 'a rock', plural: 'rocks' },
  { singular: 'a saber', plural: 'sabers' },
  { singular: 'a salad', plural: 'salads' },
  { singular: 'a sandwich', plural: 'sandwiches' },
  { singular: 'a satellite', plural: 'satellites' },
  { singular: 'a sausage', plural: 'sausages' },
  { singular: 'a scythe', plural: 'scythes' },
  { singular: 'a seed', plural: 'seeds' },
  { singular: 'a shortbow', plural: 'shortbows' },
  { singular: 'a shortsword', plural: 'shortswords' },
  { singular: 'a shotgun', plural: 'shotguns' },
  { singular: 'a shovel', plural: 'shovels' },
  { singular: 'a skyscraper', plural: 'skyscrapers' },
  { singular: 'a sledgehammer', plural: 'sledgehammers' },
  { singular: 'a smartphone', plural: 'smartphones' },
  { singular: 'a snack', plural: 'snacks' },
  { singular: 'a soft drink', plural: 'soft drinks' },
  { singular: 'a sphere', plural: 'spheres' },
  { singular: 'a square', plural: 'squares' },
  { singular: 'a staff', plural: 'staves' },
  { singular: 'a submachine gun', plural: 'submachine guns' },
  { singular: 'a taco', plural: 'tacos' },
  { singular: 'a cup of tea', plural: 'cups of tea' },
  { singular: 'a thing of unknown origin', plural: 'things of unknown origin' },
  { singular: 'a tire iron', plural: 'tire irons' },
  { singular: 'a tomb', plural: 'tombs' },
  { singular: 'a tornado', plural: 'tornadoes' },
  { singular: 'a tower', plural: 'towers' },
  { singular: 'a train', plural: 'trains' },
  { singular: 'a trebuchet', plural: 'trebuchets' },
  { singular: 'a truck', plural: 'trucks' },
  { singular: 'a typhoon', plural: 'typhoons' },
  { singular: 'a UFO', plural: 'UFOs' },
  { singular: 'a van', plural: 'vans' },
  { singular: 'a vegetable', plural: 'vegetables' },
  { singular: 'a video game', plural: 'video games' },
  { singular: 'a volcano', plural: 'volcanoes' },
  { singular: 'a voxel', plural: 'voxels' },
  { singular: 'a wagon', plural: 'wagons' },
  { singular: 'a war hammer', plural: 'war hammers' },
  { singular: 'a whirlpool', plural: 'whirlpools' },
  { singular: 'a windmill', plural: 'windmills' },
  { singular: 'a bottle of wine', plural: 'bottles of wine' },
  { singular: 'a yacht', plural: 'yachts' }
]

const setting = {
  in: [
    'Antarctica',
    'a barn',
    'a basement',
    'a black hole',
    'a bunker',
    'a cabin',
    'a castle',
    'a cave',
    'a coliseum',
    'a courtyard',
    'a dream',
    'a dungeon',
    'a factory',
    'a farmhouse',
    'a forest',
    'a fortress',
    'a graveyard',
    'a hospital',
    'a hotel',
    'a junkyard',
    'a lab',
    'a labyrinth',
    'a lighthouse',
    'a mansion',
    'a national park',
    'a network of underground tunnels',
    'a never-ending nightmare',
    'a pitch black room',
    'a quarry',
    'a rain forest',
    'a remote desert',
    'a restaurant',
    'a school',
    'a sewer',
    'a shopping mall',
    'a small village',
    'a top secret military base',
    'a tunnel',
    'a valley',
    'a war zone',
    'a wormhole',
    'an airport',
    'an alternate universe',
    'an apartment complex',
    'an elaborate maze',
    'an empty white room',
    'an office building',
    'cyberspace',
    'outer space',
    'the deepest cave on Earth',
    'the middle of nowhere',
    'virtual reality'
  ],
  on: [
    'Mars',
    'Pluto',
    'a busy street',
    'a cruise ship',
    'a farm',
    'a plantation',
    'a space station',
    'a train',
    'an airplane',
    'an asteroid',
    'an island',
    'an unidentified planet',
    'the Moon'
  ]
}

const goal = [
  'avenge your child',
  'avenge your family',
  'avenge your lover',
  'avenge your mentor',
  'become a martyr',
  'become a monster',
  'become famous',
  'become the president',
  'become the ultimate warrior',
  'build an empire',
  'complete a forbidden ritual',
  'create a monster',
  'create a new industry',
  'create a new species',
  'create a new universe',
  'create a new weapon',
  'create a new world',
  'create the perfect soldier',
  'create the ultimate warrior',
  'cure a terminal illness',
  'destroy a forbidden weapon',
  'destroy an alien civilization',
  'destroy an ancient evil',
  'destroy an incoming asteroid',
  'destroy the galaxy',
  'destroy the planet',
  'destroy the universe',
  'discover a lost civilization',
  'discover a new element',
  'discover a new mineral',
  'discover a new planet',
  'discover a new species',
  'discover a secret location',
  'discover an alien civilization',
  'discover your true identity',
  'discover your true nature',
  'earn points',
  'earn praise',
  'earn recognition',
  'earn respect',
  'establish your brand',
  'fight climate change',
  'fight evil',
  'fight off a terminal illness',
  'fight oppression',
  'find a killer',
  'find a priceless treasure',
  'find freedom',
  'find happiness',
  'find love',
  'find the fountain of youth',
  'find your real parents',
  'find yourself',
  'get revenge',
  'get rich',
  'hide an ancient weapon',
  'hide from someone',
  'hide your true intentions',
  'impress your co-workers',
  'impress your elders',
  'impress your father',
  'impress your friends',
  'impress your mentor',
  'impress your mother',
  'level up',
  'live forever',
  'make a movie',
  'make a video game',
  'open a restaurant',
  'open a wormhole',
  'prevent a viral outbreak',
  'prevent a war',
  'prevent an asteroid from colliding with Earth',
  'prevent an evil plot',
  'prevent society from collapsing',
  'prevent the apocalypse',
  'prevent the economy from collapsing',
  'prevent the end of the world',
  'reach enlightenment',
  'recover an ancient artifact',
  'redesign your website',
  'rule the country',
  'rule the galaxy',
  'rule the universe',
  'rule the world',
  'save a prince',
  'save a princess',
  'save an endangered species',
  'save the chancellor',
  'save the galaxy',
  'save the king',
  'save the president',
  'save the prime minister',
  'save the queen',
  'save the universe',
  'save the world',
  'save your city',
  'save your country',
  'save your family',
  'save your home',
  'save your lover',
  'save yourself',
  'seal away an evil power',
  'solve a murder',
  'solve a mystery',
  'start a business',
  'stop a dictator from achieving world domination',
  'stop a forbidden ritual',
  'stop a monster from devouring the entire universe',
  'stop a monster from eating you',
  'stop a monster from eating your family',
  'stop a monster from eating your lover',
  'stop a virus from spreading',
  'stop a war',
  'stop time',
  'survive',
  'survive World War III',
  'survive the apocalypse',
  'uncover a classified military project',
  'uncover a conspiracy',
  'unlock a giant door',
  'unlock a hidden power',
  'unlock the secrets of the universe',
  'unlock your true potential',
  'write a book',
  'write a song',
  'write an article',
  'write an op-ed'
]

const diversifier = [
  'a cloaked figure follows you everywhere',
  'a cloaked figure is watching you',
  'a creepy old man is watching you',
  'a creepy old woman is watching you',
  'a ghostly cat follows you everywhere',
  'a strange old man keeps trying to stop you',
  'a strange old woman keeps trying to stop you',
  'a terrifying monster is slowly coming toward you the whole time',
  'an adorable kitten keeps distracting you',
  'an adorable puppy keeps distracting you',
  'an invisible monster is stalking you the whole time',
  'an unspeakable horror is constantly chasing you',
  'creatures from another dimension constantly interrupt you',
  'everyone in the game speaks a different language',
  'everything in the game is a pun',
  'everything is being live streamed on the web',
  'everything is procedurally generated',
  'everything you do makes a pun appear on the screen',
  'everything you do triggers canned laughter',
  'everything you touch clones itself',
  'everything you touch explodes',
  'gravity is three times stronger',
  'it gets very dark very fast',
  'it gets weirder as you progress',
  'it keeps getting darker until you can\'t see anything',
  'it never ends',
  'the characters are procedurally generated',
  'the difficulty is different every time',
  'the game keeps messing with your perception',
  'the graphics get better as you progress',
  'the graphics get worse as you progress',
  'the levels are procedurally generated',
  'the story is procedurally generated',
  'the sun gives you power',
  'the world is going to end any minute',
  'there\'s a live studio audience watching the whole thing',
  'there\'s a mystery that\'s never explained',
  'there\'s no gravity',
  'you become more beautiful over time',
  'you can customize your character',
  'you can only make one mistake',
  'you can\'t hear anything',
  'you can\'t jump',
  'you can\'t lie',
  'you can\'t move',
  'you can\'t see anything',
  'you do it all with one button',
  'you don\'t have any money',
  'you gradually lose the ability to speak',
  'you gradually lose your ability to move',
  'you gradually lose your health',
  'you gradually lose your hearing',
  'you gradually lose your sight',
  'you gradually lose your strength',
  'you hate every minute of it',
  'you have no arms',
  'you have no legs',
  'you have really bad luck',
  'you have really good luck',
  'you have to avoid stressful situations',
  'you have to care for an endangered animal at the same time',
  'you have to do it alone',
  'you have to keep your heart rate down',
  'you have way more limbs than necessary',
  'you keep jumping backward in time',
  'you keep jumping forward in time',
  'you keep randomly teleporting',
  'you lose health every time you do it',
  'you lose money every time you do it',
  'you lose strength every time you do it',
  'you love every minute of it',
  'you only have 1 minute to do it',
  'you only have a week to live',
  'you\'re a ghost',
  'you\'re a giant',
  'you\'re a vampire',
  'you\'re carrying a bomb the whole time',
  'you\'re carrying a kitten the whole time',
  'you\'re carrying a puppy the whole time',
  'you\'re dead',
  'you\'re easily startled',
  'you\'re gradually becoming a monster',
  'you\'re made of cheese',
  'you\'re made of dirt',
  'you\'re made of fire',
  'you\'re made of light',
  'you\'re made of slime',
  'you\'re made of stone',
  'you\'re made of titanium',
  'you\'re made of water',
  'you\'re really clumsy',
  'you\'re slowly dying',
  'you\'re the last of your kind',
  'you\'re the last person alive',
  'you\'re the size of a fly',
  'you\'re the size of a planet',
  'you\'re the size of an atom',
  'your abilities are procedurally generated',
  'your arms are axes',
  'your arms are cats',
  'your arms are chainsaws',
  'your arms are dogs',
  'your arms are hammers',
  'your arms are machine guns',
  'your arms are paintbrushes',
  'your arms are pencils',
  'your arms are stop signs',
  'your arms are swords',
  'your arms are tentacles',
  'your sidekick is a broken robot',
  'your sidekick is a monster who can\'t stop eating',
  'your sidekick is a politician who can\'t stop lying'
]

export function generate (template) {
  const placeholders = {
    '{style:a}': randomElement(style.a),
    '{style:an}': randomElement(style.an),
    '{genre:a}': randomElement(genre.a),
    '{genre:an}': randomElement(genre.an),
    '{verb}': randomElement(verb),
    '{object:singular}': randomElement(object).singular,
    '{object:plural}': randomElement(object).plural,
    '{person:singular}': randomElement(person).singular,
    '{person:plural}': randomElement(person).plural,
    '{animal:singular}': randomElement(animal).singular,
    '{animal:plural}': randomElement(animal).plural,
    '{supernatural:singular}': randomElement(supernatural).singular,
    '{supernatural:plural}': randomElement(supernatural).plural,
    '{setting:in}': randomElement(setting.in),
    '{setting:on}': randomElement(setting.on),
    '{goal}': randomElement(goal),
    '{diversifier}': randomElement(diversifier)
  }

  return template.split(/(\{.*?\})/g).map(e => e.replace(/(\{.*?\})/, placeholders[e])).join('')
}
